// swift-tools-version: 6.4
import CompilerPluginSupport
import PackageDescription

// WireMVC — a declarative-routing Wire adapter, proposal-native. Controllers written with
// `@Controller` / verb / param / response annotations have their route registration generated by
// the `@Controller` macro onto a `some RoutableHTTPServerBuilder`, which dispatches over the
// swift-http-api-proposal server (`HTTPServer.serve`) — so a controller serves on any concrete
// proposal server (e.g. swift-server's `NIOHTTPServer`) unchanged.
//
// `@Controller` aliases `@Contributes(to: RouteKeys.handlers)`, so swift-wire's graph collates the
// controllers; `Wire.bootstrap()` returns a graph conforming to `RouteComposable`, and `WireMVC.apply`
// registers the controllers onto a caller-owned `some RoutableHTTPServerBuilder` (a router, which is
// also the proposal's request handler, so it serves) — WireMVC stays router-agnostic. Depends on
// pushed swift-wire main; `WireMVCExample` is the runnable end-to-end validation, served on
// `NIOHTTPServer` via a concrete `WireRouter` that lives in the example.
//
// tools-version 6.4 and the experimental/upcoming-feature flags match the proposal stack — its API
// is compiled with them, so a consumer needs the same to call it. Requires a Swift 6.4 toolchain.
let proposalSettings: [SwiftSetting] = [
    .strictMemorySafety(),
    .enableExperimentalFeature("SuppressedAssociatedTypesWithDefaults"),
    .enableExperimentalFeature("LifetimeDependence"),
    .enableExperimentalFeature("Lifetimes"),
    .enableUpcomingFeature("LifetimeDependence"),
    .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
    .enableUpcomingFeature("InferIsolatedConformances"),
    .enableUpcomingFeature("ExistentialAny"),
    .enableUpcomingFeature("MemberImportVisibility"),
    .enableUpcomingFeature("InternalImportsByDefault"),
]

let package = Package(
    name: "wire-mvc",
    platforms: [.macOS(.v26)],
    products: [
        .library(name: "WireMVC", targets: ["WireMVC"]),
        // The batteries-included router for the native (proposal-server) path — a concrete
        // `RoutableHTTPServerBuilder` + `HTTPServerRequestHandler`. Opt-in, so the router-agnostic
        // core (and the ServerTransport adapter) don't pull it in.
        .library(name: "WireMVCRouter", targets: ["WireMVCRouter"]),
        .library(name: "WireMVCServerTransport", targets: ["WireMVCServerTransport"]),
        // Test support for a `@WireMVCBootstrap` app — the generated `.wiremvc(_:)` suite trait stands the app
        // up on the server its mode carries and points `TestClient.current` at it. The generated
        // `_WireRoutes.swift` emits that factory (and imports this) for a test consumer, so a
        // `@WireMVCBootstrap` test target links it. Server-agnostic by default: it names only the proposal's
        // abstract `HTTPServer`, so a consumer resolves no concrete server package unless it enables the
        // `NIOHTTPServer` trait.
        .library(name: "WireMVCTesting", targets: ["WireMVCTesting"]),
        // The adapter-owned build plugin a WireMVC consumer applies (instead of swift-wire's
        // WireBuildPlugin) — it runs WireGen + WireMVCRouteGen, emitting the proxy structs + witnesses.
        .plugin(name: "WireMVCBuildPlugin", targets: ["WireMVCBuildPlugin"]),
    ],
    traits: [
        // Opt-in ServerTransport (swift-openapi-runtime) compatibility. Off by default, so the core
        // stays proposal-only and doesn't resolve OpenAPIRuntime; enable it to use the
        // `WireMVCServerTransport` adapter, which serves proposal-native WireMVC controllers on a
        // `some ServerTransport` (Hummingbird/Vapor via swift-openapi-hummingbird/-vapor).
        .trait(name: "ServerTransport"),
        // Opt-in `NIOHTTPServer` test support — the `WireMVCTestServer` conformance and the
        // `.swiftHttpServer` suite mode. Off by default so `swift-http-server` is pruned from the graph
        // of a consumer that doesn't serve on it: a framework-agnostic package depending on `WireMVC`
        // resolves no NIO stack at all. Enable it on the wire-mvc dependency to run a live suite.
        .trait(name: "NIOHTTPServer"),
    ],
    dependencies: [
        .package(url: "https://github.com/tachyonics/swift-wire.git", branch: "main"),
        .package(url: "https://github.com/apple/swift-http-api-proposal.git", .upToNextMinor(from: "0.2.0")),
        .package(
            url: "https://github.com/apple/swift-async-algorithms.git",
            exact: "1.1.5",
            traits: ["UnstableAsyncStreaming"]
        ),
        .package(url: "https://github.com/apple/swift-http-types.git", from: "1.6.0"),
        .package(url: "https://github.com/apple/swift-collections.git", from: "1.6.0"),
        .package(url: "https://github.com/swift-server/swift-http-server.git", branch: "main"),
        .package(url: "https://github.com/swift-server/swift-service-lifecycle.git", from: "2.0.0"),
        .package(url: "https://github.com/apple/swift-log.git", from: "1.13.2"),
        .package(url: "https://github.com/apple/swift-openapi-runtime.git", from: "1.7.0"),
        .package(url: "https://github.com/swiftlang/swift-syntax", branch: "release/6.4.x"),
    ],
    targets: [
        // The route codegen — the domain half of a route contributor (verbs, param bindings, response
        // modes, the middleware fold), shared verbatim by the `@Controller` macro and the
        // `WireMVCRouteGen` tool so they cannot drift. Plain SwiftSyntax (no macro surface), so both a
        // compiler-plugin macro and an executable can depend on it.
        .target(
            name: "WireMVCCodegen",
            dependencies: [
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftParser", package: "swift-syntax"),
                .product(name: "SwiftBasicFormat", package: "swift-syntax"),
                .product(name: "SwiftDiagnostics", package: "swift-syntax"),
            ]
        ),
        .macro(
            name: "WireMVCMacros",
            dependencies: [
                "WireMVCCodegen",
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftSyntaxMacros", package: "swift-syntax"),
                .product(name: "SwiftCompilerPlugin", package: "swift-syntax"),
                .product(name: "SwiftDiagnostics", package: "swift-syntax"),
            ]
        ),
        // The WireMVC route-codegen tool (Phase A domain half) — emits `RouteContributor` extensions on
        // the plugin-emitted structural proxies. A thin CLI over `WireMVCCodegen`; wired into the build
        // at the A3 cutover.
        .executableTarget(
            name: "WireMVCRouteGen",
            dependencies: ["WireMVCCodegen"]
        ),
        // The adapter-owned build plugin — runs WireGen (swift-wire) + WireMVCRouteGen (this package).
        .plugin(
            name: "WireMVCBuildPlugin",
            capability: .buildTool(),
            dependencies: [
                "WireMVCRouteGen",
                .product(name: "WireGen", package: "swift-wire"),
            ]
        ),
        .target(
            name: "WireMVC",
            dependencies: [
                "WireMVCMacros",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                // The proposal's `Middleware`/`MiddlewareBuilder`/`ChainedMiddleware`. WireMVC's
                // per-route chains are folds over these; the box they carry is WireMVC-owned (the
                // proposal ships the box only in a test module), see Middleware.swift.
                .product(name: "Middleware", package: "swift-http-api-proposal"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "BasicContainers", package: "swift-collections"),
                // The `services` collation key + `WireMVCComposable.services` surface app-scoped
                // `ServiceLifecycle` services the graph runs alongside the server.
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
            ],
            swiftSettings: proposalSettings
        ),
        // Test support for a `@WireMVCBootstrap` app — the runtime the generated `.wiremvc()` suite trait
        // calls (`WireMVCSuiteTrait` + `WireMVCTesting.serveForSuite` + `TestClient`). Serves on an ephemeral
        // port and drives real HTTP over `URLSession`, so it depends on `Foundation`. Its `serveForSuite`
        // mirrors `WireMVC.serve`'s generics so the opaque `~Copyable` handler flows in by inference, and it
        // names only the abstract `HTTPServer` + the `WireMVCTestServer` bound-port seam. The concrete
        // `NIOHTTPServer` conformance and the `.swiftHttpServer` mode are `#if NIOHTTPServer`, so with the
        // trait off this target — and every consumer of it or of `WireMVC` — resolves no server package.
        .target(
            name: "WireMVCTesting",
            dependencies: [
                "WireMVC",
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                // `HTTPRequest`/`HTTPFields` for the dispatch-side correlation-header read (H2.2b) and the
                // in-process transport's request/response heads.
                .product(name: "HTTPTypes", package: "swift-http-types"),
                // `AsyncReader`/`CallerAsyncWriter` — the in-process reader and body writer conform to them.
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                // `AsyncChannel` — the rendezvous the in-process response body streams over, so a writer
                // suspends until the test reads. That is what makes backpressure observable in process.
                .product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
                // `UniqueArray` — the in-process reader's buffer type.
                .product(name: "BasicContainers", package: "swift-collections"),
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
                // The `NIOHTTPServer: WireMVCTestServer` conformance and the `.swiftHttpServer` mode, both
                // behind the `NIOHTTPServer` trait — off by default, so this target names only the abstract
                // `HTTPServer` and the NIO stack leaves the graph entirely.
                .product(
                    name: "NIOHTTPServer",
                    package: "swift-http-server",
                    condition: .when(traits: ["NIOHTTPServer"])
                ),
                .product(name: "Logging", package: "swift-log", condition: .when(traits: ["NIOHTTPServer"])),
                // The proposal's cross-platform client, for the live transport. Same trait: a live suite
                // needs both halves, and `swift-http-api-proposal` already declares async-http-client, so
                // this adds a link dependency rather than a package.
                .product(
                    name: "AHCHTTPClient",
                    package: "swift-http-api-proposal",
                    condition: .when(traits: ["NIOHTTPServer"])
                ),
            ],
            swiftSettings: proposalSettings
        ),
        // The native-path router — concrete `RoutableHTTPServerBuilder` + `HTTPServerRequestHandler`.
        // The routing algorithm is the non-generic `RouteTable`; `WireRouter` threads the server's
        // `~Copyable` associated types. What a `@WireMVCBootstrap` `createRoutableBuilder(for:)` returns.
        .target(
            name: "WireMVCRouter",
            dependencies: [
                "WireMVC",
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
            ],
            swiftSettings: proposalSettings
        ),
        // Opt-in ServerTransport adapter — gated on the `ServerTransport` trait, so OpenAPIRuntime is
        // pruned from resolution unless a consumer enables it. Its sources are `#if ServerTransport`,
        // so the target compiles to an empty module when the trait is off.
        .target(
            name: "WireMVCServerTransport",
            dependencies: [
                "WireMVC",
                .product(name: "Wire", package: "swift-wire"),
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                // `AsyncChannel` (rendezvous → backpressure) backs the streaming response bridge.
                .product(name: "AsyncAlgorithms", package: "swift-async-algorithms"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "BasicContainers", package: "swift-collections"),
                // `apply` returns the graph's collated `[any Service]`.
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
                .product(
                    name: "OpenAPIRuntime",
                    package: "swift-openapi-runtime",
                    condition: .when(traits: ["ServerTransport"])
                ),
            ],
            swiftSettings: proposalSettings
        ),
        .testTarget(
            name: "WireMVCServerTransportTests",
            dependencies: [
                "WireMVCServerTransport",
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
            ],
            swiftSettings: proposalSettings
        ),
        // H1 — the doubles-supply runtime: `TestBindStore`, `CorrelationID`, the `withBindValues` core,
        // the correlation task-local, and `TestClient`'s header-stamping. Unit-only (no server, no key);
        // uses a dummy `Doubles` and `@testable` access to assert the built `URLRequest`.
        .testTarget(
            name: "WireMVCTestingTests",
            dependencies: [
                "WireMVCTesting",
                // The in-process transport tests hand-write an `HTTPServerRequestHandler` over the in-memory
                // associated types, so they name the proposal's server protocols and the buffer/HTTP types.
                .product(name: "HTTPAPIs", package: "swift-http-api-proposal"),
                .product(name: "HTTPTypes", package: "swift-http-types"),
                .product(name: "AsyncStreaming", package: "swift-async-algorithms"),
                .product(name: "BasicContainers", package: "swift-collections"),
                // The services-axis tests stand up a real `ServiceLifecycle` service.
                .product(name: "ServiceLifecycle", package: "swift-service-lifecycle"),
            ],
            swiftSettings: proposalSettings
        ),
        .testTarget(
            name: "WireMVCMacrosTests",
            dependencies: [
                "WireMVCMacros",
                .product(name: "SwiftSyntaxMacrosTestSupport", package: "swift-syntax"),
            ]
        ),
        .testTarget(
            name: "WireMVCCodegenTests",
            dependencies: [
                "WireMVCCodegen",
                .product(name: "SwiftSyntax", package: "swift-syntax"),
                .product(name: "SwiftParser", package: "swift-syntax"),
            ]
        ),
        .testTarget(
            name: "WireMVCRouterTests",
            dependencies: [
                "WireMVCRouter",
                .product(name: "HTTPTypes", package: "swift-http-types"),
            ],
            swiftSettings: proposalSettings
        ),
    ]
)
