public import Wire

/// A route contributor — its `registerWireRoutes` witness is generated by `@Controller`,
/// registering each of the controller's routes onto a `some HTTPServerRouteBuilder`. Not
/// written by hand (the `Wire` in the name marks it generated).
///
/// It has **no** associated types — the genericity lives on the method, over the builder — so
/// `any RouteContributor` boxes and collates through Wire's `CollectedKey`, while the builder keeps
/// the server's `~Copyable` associated `Reader`/`ResponseSender`, which can't be boxed. The
/// inverse (`~Copyable`) requirements are restated here because they don't propagate across the
/// generic boundary on their own (the proposal's own `serve` restates them the same way).
///
/// `Sendable` because a controller is an app-scoped singleton whose route handlers run
/// concurrently per request.
public protocol RouteContributor: Sendable {
    /// - Parameter coding: the app-wide coding settings, resolved at the composition root and passed
    ///   inward. A contributor uses them unless its own `@Coding` overrides them.
    ///
    ///   They are passed rather than injected because they are consumed at *leaf* sites — a
    ///   `RequestBound.bind`, a `WireMVCOutcome.json` — inside each route. Global middleware avoids this
    ///   by wrapping the finished router once, which works only because middleware composes as a
    ///   function of the request; coding has no such property, so it has to travel inward.
    func registerWireRoutes<Builder: HTTPServerRouteBuilder>(
        on builder: inout Builder,
        coding: WireMVCCoding
    ) throws
    where
        Builder.RequestContext: ~Copyable,
        Builder.Reader: ~Copyable,
        Builder.ResponseSender: ~Copyable,
        Builder.ResponseSender.Writer: ~Copyable
}

/// The collation keys namespace for WireMVC.
public enum WireMVCKeys {}

extension WireMVCKeys {
    /// The key `@Controller` aliases into — the graph collates every controller's contributor here.
    public static let routeContributors = CollectedKey<any RouteContributor>()
}
