import Testing
import WireMVCTesting

@testable import WireMVCBootstrapExample

// End-to-end proof of the generated `.wiremvc(_:)` suite trait. `WireMVCBootstrapExample` is a real
// `@WireMVCBootstrap` app whose `@main` and `.wiremvc(_:)` suite-trait factory are both generated by
// `WireMVCRouteGen`. `.swiftHttpServer` is a `NIOHTTPServer` the harness owns and binds to an ephemeral
// loopback port — the app's `createServer()` is not involved, so nothing has to `@Replaces` its
// `ServerConfig` down to port 0 and parallel suites cannot collide. Each test reaches the server through
// `TestClient.current`, proving the generated factory compiles AND the seam serves real HTTP end to end.
// The suite's tests are read-only `GET`s against a shared server, so it stays parallel.

@Suite(.wiremvc(.swiftHttpServer))
struct WithTestServerTests {
    /// `GET /hello/{name}` routes through the graph-constructed `HelloController` (its injected `Greeter`)
    /// and answers `{"message":"Hello, <name>!"}` — a real 200 over HTTP via the harness-owned suite server.
    @Test func servesHelloRouteOverEphemeralPort() async throws {
        try await withClient(for: HelloControllerClient.self) { hello in
            let greeting = try await hello.hello(name: "Alice")
            #expect(greeting.message == "Hello, Alice!")
        }
    }

    /// `GET /hello/tenant` throws `TenantMissing`, which the composition root's global
    /// `@ErrorResponse(TenantMissing.self, .badRequest)` maps — proving the global tier serves over the seam.
    @Test func globalErrorTierMapsToBadRequest() async throws {
        try await withClient(for: HelloControllerClient.self) { hello in
            let error = try await #require(throws: WireMVCRouteError.self) { try await hello.tenant() }
            #expect(error.status == .badRequest)
        }
    }

    /// An unmatched path hits the `@NotFound` `@RawRoute` fallback — a 404 with the handler's body.
    @Test func notFoundFallbackServes() async throws {
        try await withClient { client in
            let response = try await client.get("/no/such/route")
            #expect(response.status == 404)
            #expect(response.bodyText.contains("no route here"))
        }
    }
}
