import Testing
import WireMVCTesting

@testable import WireMVCBootstrapExample

// End-to-end proof of the generated `.wiremvc(_:)` suite trait. `WireMVCBootstrapExample` is a real
// `@WireMVCBootstrap` app whose `@main` and `.wiremvc(_:)` suite-trait factory are both generated by
// `WireMVCRouteGen`. `.swiftHttpServer` is a `NIOHTTPServer` the harness owns and binds to an ephemeral
// loopback port — the app's `createServer()` is not involved, so nothing has to `@Replaces` its
// `ServerConfig` down to port 0 and parallel suites cannot collide. Each test reaches the server through
// `TestClient.current`, proving the generated factory compiles AND the seam serves real HTTP end to end.
// The suite's tests are read-only `GET`s against a shared server, so it stays parallel.

@Suite(.wiremvc(.swiftHttpServer))
struct WithTestServerTests {
    /// `GET /hello/{name}` routes through the graph-constructed `HelloController` (its injected `Greeter`)
    /// and answers `{"message":"Hello, <name>!"}` — a real 200 over HTTP via the harness-owned suite server.
    @Test func servesHelloRouteOverEphemeralPort() async throws {
        try await withClient(for: HelloControllerClient.self) { hello in
            let greeting = try await hello.hello(name: "Alice")
            #expect(greeting.message == "Hello, Alice!")
        }
    }

    /// `GET /hello/tenant` throws `TenantMissing`, which the composition root's global
    /// `@ErrorResponse(TenantMissing.self, .badRequest)` maps — proving the global tier serves over the seam.
    @Test func globalErrorTierMapsToBadRequest() async throws {
        try await withClient(for: HelloControllerClient.self) { hello in
            let error = try await #require(throws: WireMVCRouteError.self) { try await hello.tenant() }
            #expect(error.status == .badRequest)
        }
    }

    /// An unmatched path hits the `@NotFound` `@RawRoute` fallback — a 404 with the handler's body.
    @Test func notFoundFallbackServes() async throws {
        try await withClient { client in
            let response = try await client.get("/no/such/route")
            #expect(response.status == 404)
            #expect(response.bodyText.contains("no route here"))
        }
    }
}

// Response headers over the wire, on the harness-owned server — the only place the whole chain is real:
// the annotation tiers, the handler's return, and a middleware's registered contributions all resolving
// into one response head.
@Suite(.wiremvc(.swiftHttpServer))
struct ResponseHeaderOverTheWireTests {
    /// The tier order, end to end. `/hello/stamped` sets `x-stamp: route` as a route constant and
    /// `StampMiddleware` sets it again — middleware applies last, so the middleware's value is what ships.
    /// Its `Set-Cookie` is registered on the way *in* and evaluated at drain, after the handler recorded the
    /// name, which is the thing that cannot be done by mutating a response after `next`.
    @Test func middlewareContributionsBeatRouteConstantsAndSeeTheHandler() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/stamped/Ada")
            #expect(response.status == 200)
            let fields = try #require(response.head?.headerFields)
            #expect(fields[values: .init("x-stamp")!] == ["middleware"], "middleware applies after the route")
            #expect(fields[values: .cacheControl] == ["no-store"], "a field only the route set survives")
            #expect(fields[values: .setCookie] == ["greeted=Ada; Path=/"], "the deferred closure saw the handler")
        }
    }

    /// A route with constants and no middleware still gets them, and still gets the JSON content type that
    /// `WireMVCOutcome.json` seeds.
    @Test func routeConstantsShipWithoutMiddleware() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/cached/Ada")
            let fields = try #require(response.head?.headerFields)
            #expect(fields[values: .cacheControl] == ["public, max-age=60"])
            #expect(fields[.contentType] == "application/json")
        }
    }

    /// The computed redirect: a bodiless response tuple, no response annotation, `Location` computed by the
    /// handler. Asserted *through* the redirect rather than on it — `TestClient` is URLSession-backed and
    /// follows 3xx, so the 302 and its `Location` are not observable here. Landing on the greeting for
    /// "Ada" is only possible if the handler's computed `Location` was both emitted and correct; the head
    /// itself is pinned by the codegen golden instead.
    ///
    /// The harness not being able to see a redirect is a real gap — a no-follow mode belongs in
    /// `WireMVCTesting`, since redirects are most of what the blocked web examples do.
    @Test func bodilessTupleRedirectsToTheComputedLocation() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/moved/Ada")
            #expect(response.status == 200)
            #expect(response.bodyText.contains("Hello, Ada!"))
        }
    }
}

// The global tier reaching responses it could not reach before. `AccessLog` is the app's global
// `@Middleware`; it contributes `x-served-by` on the way in, and the courier carries that registry from the
// front layer down to whatever writes the response.
@Suite(.wiremvc(.swiftHttpServer))
struct GlobalMiddlewareHeaderTests {
    /// A route with **no `@Middleware` of its own** — the case that matters, because it is most routes.
    /// Its terminal drains the registry the front layer created, so the global contribution lands.
    @Test func globalContributionReachesARouteWithNoMiddleware() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/cached/Ada")
            #expect(response.status == 200)
            #expect(response.head?.headerFields[.init("x-served-by")!] == "wire-mvc")
        }
    }

    /// A `@RawRoute` writes its own head, so there is no outcome to inject into — its sender is wrapped
    /// instead. Without that, a global header would vanish on every raw route.
    @Test func globalContributionReachesARawRoute() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/raw/Ada")
            #expect(response.status == 200)
            #expect(response.head?.headerFields[.init("x-served-by")!] == "wire-mvc")
        }
    }

    /// The `@NotFound` fallback must be `@RawRoute`, so before the sender wrapper it was the one response
    /// that could never carry a global header — exactly where CORS or a security header is wanted.
    @Test func globalContributionReachesTheNotFoundFallback() async throws {
        try await withClient { client in
            let response = try await client.get("/no/such/route")
            #expect(response.status == 404)
            #expect(response.head?.headerFields[.init("x-served-by")!] == "wire-mvc")
        }
    }
}
