import HTTPTypes
import Testing
import WireMVCTesting

@testable import WireMVCBootstrapExample

// End-to-end proof of the generated `.wiremvc(_:)` suite trait. `WireMVCBootstrapExample` is a real
// `@WireMVCBootstrap` app whose `@main` and `.wiremvc(_:)` suite-trait factory are both generated by
// `WireMVCRouteGen`. `.swiftHttpServer` is a `NIOHTTPServer` the harness owns and binds to an ephemeral
// loopback port — the app's `createServer()` is not involved, so nothing has to `@Replaces` its
// `ServerConfig` down to port 0 and parallel suites cannot collide. Each test reaches the server through
// `TestClient.current`, proving the generated factory compiles AND the seam serves real HTTP end to end.
// The suite's tests are read-only `GET`s against a shared server, so it stays parallel.

@Suite(.wiremvc(.swiftHttpServer))
struct WithTestServerTests {
    /// `GET /hello/{name}` routes through the graph-constructed `HelloController` (its injected `Greeter`)
    /// and answers `{"message":"Hello, <name>!"}` — a real 200 over HTTP via the harness-owned suite server.
    @Test func servesHelloRouteOverEphemeralPort() async throws {
        try await withClient(for: HelloControllerClient.self) { hello in
            let greeting = try await hello.hello(name: "Alice")
            #expect(greeting.message == "Hello, Alice!")
        }
    }

    /// `GET /hello/tenant` throws `TenantMissing`, which the composition root's global
    /// `@ErrorResponse(TenantMissing.self, .badRequest)` maps — proving the global tier serves over the seam.
    @Test func globalErrorTierMapsToBadRequest() async throws {
        try await withClient(for: HelloControllerClient.self) { hello in
            let error = try await #require(throws: WireMVCRouteError.self) { try await hello.tenant() }
            #expect(error.status == .badRequest)
        }
    }

    /// An unmatched path hits the `@NotFound` `@RawRoute` fallback — a 404 with the handler's body.
    @Test func notFoundFallbackServes() async throws {
        try await withClient { client in
            let response = try await client.get("/no/such/route")
            #expect(response.status == 404)
            #expect(response.bodyText.contains("no route here"))
        }
    }
}

// Response headers over the wire, on the harness-owned server — the only place the whole chain is real:
// the annotation tiers, the handler's return, and a middleware's registered contributions all resolving
// into one response head.
@Suite(.wiremvc(.swiftHttpServer))
struct ResponseHeaderOverTheWireTests {
    /// The tier order, end to end. `/hello/stamped` sets `x-stamp: route` as a route constant and
    /// `StampMiddleware` sets it again — middleware applies last, so the middleware's value is what ships.
    /// Its `Set-Cookie` is registered on the way *in* and evaluated at drain, after the handler recorded the
    /// name, which is the thing that cannot be done by mutating a response after `next`.
    @Test func middlewareContributionsBeatRouteConstantsAndSeeTheHandler() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/stamped/Ada")
            #expect(response.status == 200)
            let fields = try #require(response.head?.headerFields)
            #expect(fields[values: .init("x-stamp")!] == ["middleware"], "middleware applies after the route")
            #expect(fields[values: .cacheControl] == ["no-store"], "a field only the route set survives")
            #expect(fields[values: .setCookie] == ["greeted=Ada; Path=/"], "the deferred closure saw the handler")
        }
    }

    /// **The same contributions on a refusal.** `/hello/refused` folds the same middleware and throws;
    /// the composition root maps it to `400`. Every field a served response would have carried has to be
    /// on the refusal too, and for a while none of them were: the terminal resolved `headerFields` against
    /// the drain on the success path and built a bare `WireMVCOutcome.status(…)` in its `catch`, so a
    /// middleware's contributions survived a `200` and vanished from every `@ErrorResponse` status.
    ///
    /// Backwards, because the error path is the one that needs them most — a cross-origin caller cannot
    /// read a `403` whose `Access-Control-Allow-Origin` was dropped. The gate path never had the bug:
    /// `respondingWith` drains, which is why a middleware that answers *itself* kept its fields while one
    /// that merely contributed to a mapped throw lost them.
    ///
    /// The deferred `Set-Cookie` is asserted too, and it is the sharper half: it proves the drain runs
    /// rather than that some stashed value was replayed, since the closure can only produce a cookie by
    /// reading what the handler wrote before it threw.
    @Test func middlewareContributionsSurviveAMappedRefusal() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/refused/Ada")
            #expect(response.status == 400, "the composition root's global mapping answered")
            let fields = try #require(response.head?.headerFields)
            #expect(fields[values: .init("x-stamp")!] == ["middleware"], "contributed on the way in")
            #expect(fields[values: .setCookie] == ["greeted=Ada; Path=/"], "the deferred closure ran at drain")
        }
    }

    /// A route with constants and no middleware still gets them, and still gets the JSON content type that
    /// `WireMVCOutcome.json` seeds.
    @Test func routeConstantsShipWithoutMiddleware() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/cached/Ada")
            let fields = try #require(response.head?.headerFields)
            #expect(fields[values: .cacheControl] == ["public, max-age=60"])
            #expect(fields[.contentType] == "application/json")
        }
    }

    /// The computed redirect: a bodiless response tuple, no response annotation, `Location` computed by the
    /// handler. Asserted *through* the redirect rather than on it — `TestClient` is URLSession-backed and
    /// follows 3xx, so the 302 and its `Location` are not observable here. Landing on the greeting for
    /// "Ada" is only possible if the handler's computed `Location` was both emitted and correct; the head
    /// itself is pinned by the codegen golden instead.
    ///
    /// The harness not being able to see a redirect is a real gap — a no-follow mode belongs in
    /// `WireMVCTesting`, since redirects are most of what the blocked web examples do.
    @Test func bodilessTupleRedirectsToTheComputedLocation() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/moved/Ada")
            #expect(response.status == 200)
            #expect(response.bodyText.contains("Hello, Ada!"))
        }
    }
}

// The global tier reaching responses it could not reach before. `AccessLog` is the app's global
// `@Middleware`; it contributes `x-served-by` on the way in, and the courier carries that registry from the
// front layer down to whatever writes the response.
@Suite(.wiremvc(.swiftHttpServer))
struct GlobalMiddlewareHeaderTests {
    /// A route with **no `@Middleware` of its own** — the case that matters, because it is most routes.
    /// Its terminal drains the registry the front layer created, so the global contribution lands.
    @Test func globalContributionReachesARouteWithNoMiddleware() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/cached/Ada")
            #expect(response.status == 200)
            #expect(response.head?.headerFields[.init("x-served-by")!] == "wire-mvc")
        }
    }

    /// A `@RawRoute` writes its own head, so there is no outcome to inject into — its sender is wrapped
    /// instead. Without that, a global header would vanish on every raw route.
    @Test func globalContributionReachesARawRoute() async throws {
        try await withClient { client in
            let response = try await client.get("/hello/raw/Ada")
            #expect(response.status == 200)
            #expect(response.head?.headerFields[.init("x-served-by")!] == "wire-mvc")
        }
    }

    /// The `@NotFound` fallback must be `@RawRoute`, so before the sender wrapper it was the one response
    /// that could never carry a global header — exactly where CORS or a security header is wanted.
    @Test func globalContributionReachesTheNotFoundFallback() async throws {
        try await withClient { client in
            let response = try await client.get("/no/such/route")
            #expect(response.status == 404)
            #expect(response.head?.headerFields[.init("x-served-by")!] == "wire-mvc")
        }
    }

    // MARK: - The prepare() pre-step

    /// The pre-step ran, and ran *before* any binding was constructed — the property that makes it usable
    /// for `LoggingSystem.bootstrap`, which must precede the first log call.
    @Test func prepareRanBeforeAnyBindingWasConstructed() {
        #expect(StartupProbe.prepareCount >= 1)
        #expect(StartupProbe.ranBeforeConstruction)
    }

    /// Its return value is the graph's `inputs:`, so both inputs reached a binding — the unkeyed
    /// `ServerConfig` by type and the keyed `releaseChannel` through `@Bind`.
    @Test func inputsFromPrepareReachedTheGraph() {
        #expect(StartupSummary.value == "127.0.0.1:8080|stable")
    }

    /// Exactly once per process, however many suites run. `prepare()` does once-per-process work
    /// (`LoggingSystem.bootstrap` traps on a second call), and a suite trait rebuilds the app at every
    /// suite entry — so the generated test entry routes it through `WireMVCTesting.preparedOnce`. This
    /// bundle has several `.wiremvc()` suites, which is what makes the assertion meaningful.
    @Test func prepareRanOnlyOncePerProcess() {
        #expect(StartupProbe.prepareCount == 1)
    }
}
